### ISSUE TITLE
Cannot upload values if there was an error in previous ones

### ISSUE THREAD

**Issue by bgoglin** [TrainerDex/Website#479]
Hello
I am trying to update all my medal values from the website. I made a mistake in my sightseer value last time, I put the backpacker value  instead. Now when I try to update the values, the website says the new value (1602) is lower than the previous one (34691). That's correct. Hence I check the checkbox saying that I am sure and I have verified the values, but it won't let me upload the new values. How am I supposed to fix this?
Thanks

**Comment by TurnrDev** [comment]
Hi @bgoglin,

This is by design so that I, or other admins, can fix the data correctly. However I am working on an update to delete old data. I can fix the data for you if you can confirm what you username is on the website.

Thank you

**Comment by bgoglin** [comment]
Hello
The username is "Briculor". If you remove 34691 from sightseer on march 27th, things should be fine.
Thanks

**Comment by TurnrDev** [comment]
@bgoglin All sorted now. I'm gonna close this issue, but if you need any more help feel free to reopen it :)
