### ISSUE TITLE
change discord name for existing Trainer

### ISSUE THREAD

**Issue by bgoglin** [TrainerDex/Website#569]
Hello
Our local trainer "Tyrolion1" lost his discord account. He was registered in the trainerdex bot with this account "tyrolion1#5763". Can you change that into his new discord account ".tyrolion1" so that he may update his stats from discord again?
Thanks

**Comment by TurnrDev** [comment]
He will need message in the Discord server as I am unable to do that with just a username.

**Comment by bgoglin** [comment]
Do you mean our local discord server (you left it a couple weeks ago) or the main Trainerdex one?

**Comment by TurnrDev** [comment]
The main TrainerDex support server
